services:
  - type: web
    name: apex-core-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: MONGO_URI

        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://apex-core-frontend.onrender.com
      - key: ADMIN_URL
        value: https://apex-core-admin.onrender.com
      - key: BACKEND_URL
        value: https://apex-core-backend.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  - type: web
    name: apex-core-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://apex-core-backend.onrender.com

  - type: web
    name: apex-core-admin
    runtime: static
    rootDir: admin
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://apex-core-backend.onrender.com
